const SET_EMAIL = "SET_EMAIL";
const SET_PASSWORD = "SET_PASSWORD";
const LOGIN = "LOGIN";
const LOGIN_FAIL = "LOGIN_FAIL";
const CREATE_ACCOUNT = "CREATE_ACCOUNT";
const CREATE_ACCOUNT_FAIL = "CREATE_ACCOUNT_FAIL";

export default{
  SET_EMAIL,
  SET_PASSWORD,
  LOGIN,
  LOGIN_FAIL,
  CREATE_ACCOUNT,
  CREATE_ACCOUNT_FAIL
}