const SET_SANITY = "SET_SANITY";
const SET_GAMEOVER = "SET_GAMEOVER";
const SET_EMAIL = "SET_EMAIL";
const SET_PASSWORD = "SET_PASSWORD";
const SET_GAMESCORE = "SET_GAMESCORE";
const UPDATE_HIGHSCORE = "UPDATE_HIGHSCORE";
const UPDATE_LEADERBOARD = "UPDATE_LEADERBOARD";
const SEND_GAMESCORE = "SEND_GAMESCORE";
const LOGIN = "LOGIN";
const LOGIN_FAIL = "LOGIN_FAIL";
const CREATE_ACCOUNT = "CREATE_ACCOUNT";
const CREATE_ACCOUNT_FAIL = "CREATE_ACCOUNT_FAIL";

export default{
  SET_SANITY,
  SET_GAMEOVER,
  SET_EMAIL,
  SET_PASSWORD,
  SET_GAMESCORE,
  UPDATE_HIGHSCORE,
  UPDATE_LEADERBOARD,
  SEND_GAMESCORE,
  LOGIN,
  LOGIN_FAIL,
  CREATE_ACCOUNT,
  CREATE_ACCOUNT_FAIL
}