const LOGIN = "LOGIN";
const LOGIN_FAIL = "LOGIN_FAIL";
const CREATE_ACCOUNT = "CREATE_ACCOUNT";
const CREATE_ACCOUNT_FAIL = "CREATE_ACCOUNT_FAIL";

export default{
  LOGIN,
  LOGIN_FAIL,
  CREATE_ACCOUNT,
  CREATE_ACCOUNT_FAIL
}